--- # yaml config for exposing global constants
    # dist stands for probability distribution

app: "---------| KProducer |---------"

limit:
  articles: 50
  users: 1000

jars: "vendor/"
data: "data/"

servers:
  kafka:  
    host: 127.0.0.1
    port: "9092"
  redis:
    host: 127.0.0.1
    port: "6379"
    db: 3
  zookeeper:
    host: 127.0.0.1
    port: "2181"
  web:
    host: 127.0.0.1
    port: "4000"
  graphing_sockets:
    metric1:
      host: 127.0.1.1
      port: 33331
    metric2:
      host: 127.0.1.1
      port: 33332
    metric3:
      host: 127.0.1.1
      port: 33333
    metric4:
      host: 127.0.1.1
      port: 33334

actions: 
  names:
    - Purchasse
    - Bookmark
    - Comment
    - Click
  dist: [0,0,0,100]


cards: # debit cards
  names:
    - MasterCard
    - Visa
    - Maestro
  dist: [30,40,30] 


promotions:
  names:
    - promo_A
    - promo_B
    - promo_0 # for those who bought without promotions
  dist: [50, 30, 20]


quantities:
  limsup: 100 # superior limit
  values: [1, 2, 3, 4] 
  static: false
  # when static is false:
  # values.pop()
  # values.append(randint(liminf, limsup))
  dist: [25,15,15, 45]


data_comment: # number of comment in comments.csv
  size: 744
